---
- name: Install redis for Ubuntu
  hosts: "{{ target_host | default('localhost') }}"
  tasks:
    
    - name: Apt for Prerequisites
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - lsb-release
    - name: Add Repository for Apt
      block:
      - name: Add GPG Keyring
        ansible.builtin.shell: curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
      - name:
        ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
    - name: Apt for Redis
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - redis