---
  - name: Update Ubuntu Package
    hosts: "{{ target | default('localhost') }}"
    tasks:

     - name: Run the equivalent of "apt-get update" as a separate step
       ansible.builtin.apt:
         update_cache: yes
       when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04" or
             ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

     - name: Run the equivalent of "apt-get upgrade" as a separate step
       ansible.builtin.apt:
         name: "*"
         state: latest
         autoremove: yes
         autoclean: yes
       when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04" or
             ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
     
     - name: Not Support
       debug:
         msg: "This is not an Ubuntu 20.04 or 22.04 system."
       when: ansible_distribution != 'Ubuntu' or (ansible_distribution_version != '20.04' and ansible_distribution_version != '22.04')
